{% set name = "covdrugsim" %}
{% set version = "1.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/covdrugsim-{{ version }}.tar.gz
  sha256: 389bf0c5fa128cb76aa4055ca13f08dbbbc7616546ff99a09837cae06f44aed1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.7.1
    - numpy >=1.25.0
    - pandas >=2.0.2
    - seaborn >=0.12.2

test:
  imports:
    - covdrugsim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jon-Ting/covdrugsim
  summary: Package to automate quantum mechanical calculations and molecular dynamics simulations of covalent drugs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    CovDrugSim is a package that provides functionalities to automate the quantum mechanical calculations and molecular dynamics simulations of covalent drugs.
  doc_url: https://covdrugsim.readthedocs.io/
  dev_url: https://github.com/Jon-Ting/covdrugsim

extra:
  recipe-maintainers:
    - Jon-Ting
